import { fileURLToPath } from 'node:url';

export default defineNuxtConfig({
  extends: ['@tilana/ui-nuxt'],
  modules: ['@nuxt/eslint'],
  alias: {
    '@app': fileURLToPath(new URL('./app', import.meta.url)),
    '@server': fileURLToPath(new URL('./server', import.meta.url)),
  },
  compatibilityDate: '2026-08-19',
  telemetry: false,
  runtimeConfig: {
    databaseUrl: '',
    supabaseUrl: '',
    supabasePublishableKey: '',
    supabaseServiceRoleKey: '',
    contactAllowedOrigins:
      'http://127.0.0.1:4321,http://localhost:4321,https://tilanavantonder.co.za,https://www.tilanavantonder.co.za',
    turnstileSecretKey: '',
    contactIpHashSecret: '',
    trustedClientIpHeader: process.env.NODE_ENV === 'production' ? 'fly-client-ip' : '',
    contactTurnstileRequired: process.env.NODE_ENV === 'production',
    emailFromAddress: '',
    emailFromName: 'Tilana van Tonder website',
    contactNotificationEnabled: false,
    contactNotificationTo: 'tilanavantonder@gmail.com',
    newsletterFromEmail: '',
    newsletterDevelopmentRecipient: '',
    newsletterApiBaseUrl: 'http://127.0.0.1:3001',
    newsletterSiteUrl: 'http://127.0.0.1:4321',
    customerAccessDevelopmentRecipient: '',
    customerNotificationsEnabled: false,
    invoiceBillingEnabled: false,
    invoiceDevelopmentRecipient: '',
    paystackSecretKey: '',
    paystackEnvironment: 'test',
    paystackRecoveryEnabled: false,
    paystackRecoveryToken: '',
    paystackRecoveryAlertTo: '',
    paystackCallbackUrl: 'http://127.0.0.1:4321/checkout/complete',
    accountBaseUrl: 'http://127.0.0.1:3001',
    r2AccountId: '',
    r2PublicMediaBucket: '',
    r2PublicMediaBaseUrl: '',
    r2PrivateProgramBucket: '',
    r2DownloadAccessKeyId: '',
    r2DownloadSecretAccessKey: '',
    r2UploadAccessKeyId: '',
    r2UploadSecretAccessKey: '',
    public: {
      siteUrl: 'http://127.0.0.1:4321',
    },
  },
  devtools: {
    enabled: false,
  },
  colorMode: {
    preference: 'system',
    fallback: 'light',
  },
  routeRules: {
    '/dashboard/**': { headers: { 'cache-control': 'private, no-store' } },
    '/contacts/**': { headers: { 'cache-control': 'private, no-store' } },
    '/programs/**': { headers: { 'cache-control': 'private, no-store' } },
    '/invoices/**': { headers: { 'cache-control': 'private, no-store' } },
    '/api-docs': { headers: { 'cache-control': 'private, no-store' } },
    '/api-docs/**': { headers: { 'cache-control': 'private, no-store' } },
    '/api/auth/**': { headers: { 'cache-control': 'private, no-store' } },
    '/api/admin/**': { headers: { 'cache-control': 'private, no-store' } },
    '/api/public/**': { headers: { 'cache-control': 'public, max-age=60, s-maxage=300, stale-while-revalidate=600' } },
    '/api/checkout/**': { headers: { 'cache-control': 'no-store' } },
    '/api/webhooks/**': { headers: { 'cache-control': 'no-store' } },
    '/api/internal/**': { headers: { 'cache-control': 'private, no-store' } },
    '/account/**': { headers: { 'cache-control': 'private, no-store' } },
    '/api/customer/**': { headers: { 'cache-control': 'private, no-store' } },
  },
  app: {
    head: {
      title: 'Tilana Admin',
      link: [{ rel: 'icon', type: 'image/svg+xml', href: '/favicon.svg' }],
      meta: [
        {
          name: 'description',
          content: 'Private administration portal for Tilana van Tonder.',
        },
      ],
    },
  },
  eslint: {
    config: {
      autoInit: false,
    },
  },
});
